defaults:
    -
        scope:
            path: ""
        values:
            lang: en
            layout: default
    -
        scope:
            path: uk
        values:
            lang: uk
    -
        scope:
            path: ru
        values:
            lang: ru

exclude: [Makefile, README.md]

url: http://example.com
baseurl: ""

lang: en
direction: ltr

locales:
    en: English
    uk: Українська
    ru: Русский

title:
    en: Test site
    uk: Тестовий сайт
    ru: Тестовый сайт

footer:
    en: © Dmitry K.
    uk: © Дмитро К.
    ru: © Дмитрий К.
