defaults:
    -
        scope:
            path: ""
        values:
            lang: en
            layout: default
    -
        scope:
            path: uk
        values:
            lang: uk
    -
        scope:
            path: ru
        values:
            lang: ru

url: http://example.com
baseurl: "/path"

lang: en
direction: ltr

locales:
    en: English
    uk: Українська
    ru: Русский

footer:
    en: © Dmitry K.
    uk: © Дмитро К.
    ru: © Дмитрий К.
