defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: page
  -
    scope:
      path: uk
    values:
      lang: uk
  -
    scope:
      path: ru
    values:
      lang: ru

exclude: [Makefile, README.md]

url: http://example.com
baseurl: ""
timezone: Europe/Kiev
lang: en
direction: ltr
title: &siteTitle Test site
footer: &siteFooter © Dmitry K.

i18n_title:
  en: &siteTitle
  uk: Тестовий сайт
  ru: Тестовый сайт

i18n_lang_names:
  en: English
  uk: Українська
  ru: Русский

i18n_footer:
  en: &siteFooter
  uk: © Дмитро К.
  ru: © Дмитрий К.
